/**
 * Production Creative Browser — types + sample data + pure logic (Sprint 63).
 *
 * Reuses media + employees types. Deterministic sample creatives (no backend, no
 * fake analytics dashboards — only optional illustrative metric badges). Pure
 * filter/search/sort helpers.
 */

import type { MediaSource, PerformanceMetric, PlatformId } from "@/components/studio/media";
import type { EmployeeId } from "@/components/studio/employees/types";

export type CreativeStatusId = "generated" | "pending" | "approved" | "archived";
export type CreativeFilter =
  | "all"
  | "favorites"
  | "recent"
  | "archived"
  | "approved"
  | "pending"
  | "generated"
  | "collections";
export type CreativeSortId = "recent" | "name" | "version";
export type CreativeView = "grid" | "list";

export interface CreativeItem {
  id: string;
  title: string;
  media: MediaSource;
  platform: PlatformId;
  status: CreativeStatusId;
  ownerId: EmployeeId;
  version: number;
  variants: number;
  tags: string[];
  bookmarked: boolean;
  favorite: boolean;
  recent: boolean;
  /** Optional illustrative performance pills (none for most — no fake analytics). */
  metrics?: PerformanceMetric[];
  /** Drives the deterministic forecast chip. */
  budget: number;
  createdAt: number;
  /* ── Optional inspector metadata (additive; graceful "—" when absent) ── */
  brand?: string;
  audience?: string;
  campaign?: string;
  objective?: string;
  language?: string;
  history?: { at: number; text: string }[];
}

const T = (d: number) => Date.parse(`2026-06-${String(d).padStart(2, "0")}T09:00:00Z`);
const V: MediaSource = { kind: "video" };
const I: MediaSource = { kind: "image" };

export const SAMPLE_CREATIVES: CreativeItem[] = [
  { id: "cr1", title: "Problem-first hook", media: V, platform: "reels", status: "approved", ownerId: "creative-director", version: 3, variants: 5, tags: ["hook", "win-back"], bookmarked: true, favorite: true, recent: true, metrics: [{ label: "CTR", value: "3.2%", tone: "positive" }], budget: 8000, createdAt: T(20), brand: "Aurora", audience: "Lapsed buyers", campaign: "Spring Sale", objective: "Conversions", language: "English", history: [{ at: T(20), text: "Generated by Theo" }, { at: T(20), text: "Brand check passed" }, { at: T(20), text: "Approved" }] },
  { id: "cr2", title: "Founder story", media: V, platform: "tiktok", status: "generated", ownerId: "copywriter", version: 1, variants: 3, tags: ["trust", "ugc"], bookmarked: false, favorite: false, recent: true, budget: 5000, createdAt: T(19) },
  { id: "cr3", title: "Before / after", media: I, platform: "shorts", status: "pending", ownerId: "automation", version: 2, variants: 4, tags: ["proof"], bookmarked: false, favorite: true, recent: true, metrics: [{ label: "ROAS", value: "3.6x", tone: "neutral" }], budget: 6500, createdAt: T(18) },
  { id: "cr4", title: "Unboxing", media: V, platform: "reels", status: "generated", ownerId: "creative-director", version: 1, variants: 2, tags: ["curiosity"], bookmarked: true, favorite: false, recent: false, budget: 4000, createdAt: T(16) },
  { id: "cr5", title: "Comparison", media: I, platform: "meta", status: "approved", ownerId: "media-buyer", version: 4, variants: 6, tags: ["consideration"], bookmarked: false, favorite: false, recent: false, metrics: [{ label: "CTR", value: "2.4%", tone: "neutral" }], budget: 9000, createdAt: T(15) },
  { id: "cr6", title: "Testimonial", media: V, platform: "tiktok", status: "pending", ownerId: "copywriter", version: 2, variants: 3, tags: ["social-proof", "ugc"], bookmarked: false, favorite: false, recent: false, budget: 5500, createdAt: T(14) },
  { id: "cr7", title: "Seasonal teaser", media: I, platform: "youtube", status: "archived", ownerId: "creative-director", version: 5, variants: 2, tags: ["festive"], bookmarked: false, favorite: false, recent: false, budget: 3000, createdAt: T(10) },
  { id: "cr8", title: "Quick demo", media: V, platform: "shorts", status: "generated", ownerId: "automation", version: 1, variants: 4, tags: ["demo"], bookmarked: true, favorite: true, recent: true, metrics: [{ label: "CTR", value: "3.9%", tone: "positive" }], budget: 7000, createdAt: T(17) },
  { id: "cr9", title: "Offer spotlight", media: I, platform: "meta", status: "approved", ownerId: "media-buyer", version: 2, variants: 3, tags: ["offer"], bookmarked: false, favorite: false, recent: false, budget: 8500, createdAt: T(12) },
  { id: "cr10", title: "Recovery angle", media: V, platform: "reels", status: "pending", ownerId: "brand-guardian", version: 1, variants: 2, tags: ["recover"], bookmarked: false, favorite: false, recent: true, budget: 6000, createdAt: T(13) },
];

export interface CreativeCollection {
  id: string;
  label: string;
  count: number;
}

export const COLLECTIONS: CreativeCollection[] = [
  { id: "top", label: "Top performers", count: 3 },
  { id: "ugc", label: "UGC hooks", count: 4 },
  { id: "festive", label: "Festive", count: 2 },
];

/* ── Pure filter / search / sort ─────────────────────────────────────────── */
export function filterCreatives(items: CreativeItem[], filter: CreativeFilter): CreativeItem[] {
  switch (filter) {
    case "favorites":
      return items.filter((c) => c.favorite);
    case "recent":
      return items.filter((c) => c.recent);
    case "archived":
      return items.filter((c) => c.status === "archived");
    case "approved":
      return items.filter((c) => c.status === "approved");
    case "pending":
      return items.filter((c) => c.status === "pending");
    case "generated":
      return items.filter((c) => c.status === "generated");
    case "all":
    case "collections":
    default:
      return items;
  }
}

export function searchCreatives(items: CreativeItem[], q: string): CreativeItem[] {
  const s = q.trim().toLowerCase();
  if (!s) return items;
  return items.filter(
    (c) => c.title.toLowerCase().includes(s) || c.tags.some((t) => t.toLowerCase().includes(s))
  );
}

export function sortCreatives(items: CreativeItem[], sort: CreativeSortId): CreativeItem[] {
  const out = [...items];
  if (sort === "name") out.sort((a, b) => a.title.localeCompare(b.title));
  else if (sort === "version") out.sort((a, b) => b.version - a.version);
  else out.sort((a, b) => b.createdAt - a.createdAt);
  return out;
}
